Repository Hanaro-Eureka/HPS, pull requests merged in 2025-06, with the labels that each got.

#3 [Feat] 국민연금 페이지 Slider atoms 컴포넌트 구현
  hps/.storybook/preview.ts
  hps/app/page1/hooks/.keep
  hps/app/page1/utils/.keep
  hps/app/pension/apis/.keep
  hps/app/pension/components/Slider.tsx
  hps/app/pension/constants/.keep
  hps/app/pension/hooks/.keep
  hps/app/pension/utils/.keep
  hps/package.json
  hps/pnpm-lock.yaml
  hps/stories/Button.stories.ts
  hps/stories/Button.tsx
  hps/stories/Header.stories.ts
  hps/stories/Header.tsx
  hps/stories/Page.stories.ts
  hps/stories/Page.tsx
  hps/stories/Slider.stories.tsx
  hps/stories/assets/accessibility.png
  hps/stories/assets/accessibility.svg
  hps/stories/assets/addon-library.png
  hps/stories/assets/assets.png
  hps/stories/assets/avif-test-image.avif
  hps/stories/assets/context.png
  hps/stories/assets/discord.svg
  hps/stories/assets/docs.png
  hps/stories/assets/figma-plugin.png
  hps/stories/assets/github.svg
  hps/stories/assets/share.png
  hps/stories/assets/styling.png
  hps/stories/assets/testing.png
  hps/stories/assets/theming.png
  hps/stories/assets/tutorials.svg
  hps/stories/assets/youtube.svg
  hps/stories/button.css
  hps/stories/header.css
  hps/stories/page.css
  hps/styles/globals.css
  hps/styles/tailwind.config.ts
Labels: feat, design

#10 Feat: Button atom 구현 & storybook 적용
  hps/components/atoms/Button.tsx
  hps/stories/Button.stories.tsx
Labels: feat, design

#13 [Feat] Input atom구현 & Stroybook 적용
  hps/components/atoms/Input.tsx
  hps/stories/Input.stories.tsx
Labels: feat, design

#21 [Feat] Login page 퍼블리싱
  hps/app/globals.css
  hps/app/login/page.tsx
  hps/app/page.tsx
  hps/components/atoms/Button.tsx
  hps/components/atoms/Input.tsx
Labels: feat, design

#28 [Init] DB prisma ORM 적용 & dummy Data 적용
  hps/.gitignore
  hps/backup_hps.sql
  hps/package.json
  hps/pnpm-lock.yaml
  hps/prisma/schema.prisma
Labels: docs

#31 [Design] global.css에 폰트&색상 적용, CheckboxText 수정
  hps/app/globals.css
  hps/app/tailwind.config.ts
  hps/components/molcules/CheckBoxText.tsx
  hps/public/fonts/Hana2-Bold.otf
  hps/public/fonts/Hana2-CM.otf
  hps/public/fonts/Hana2-Heavy.otf
  hps/public/fonts/Hana2-Light.otf
  hps/public/fonts/Hana2-Medium.otf
  hps/public/fonts/Hana2-Regular.otf
  hps/stories/CheckBoxText.stories.tsx
Labels: chore, design

#20 [Feat] Chart 컴포넌트 구현 & Storybook 작성
  hps/.gitignore
  hps/components/molcules/BarGraph.tsx
  hps/components/molcules/LineGraph.tsx
  hps/components/molcules/SalaryBarGraph.tsx
  hps/package.json
  hps/pnpm-lock.yaml
  hps/stories/BarGraph.stories.tsx
  hps/stories/LineGraph.stories.tsx
  hps/stories/SalaryBarGraph.stories.tsx
Labels: feat, design

#35 [Design] 글꼴, 색상 변경 완료
  hps/app/login/page.tsx
  hps/app/mypage/components/ProfileItem.tsx
  hps/app/mypage/page.tsx
  hps/app/pension/components/Slider.tsx
  hps/components/atoms/Input.tsx
  hps/components/molcules/List.tsx
  hps/components/molcules/ListItem.tsx
Labels: design

#29 [Feat] 연말정산 페이지 예상 공제/환급액 기능 구현
  hps/app/globals.css
  hps/app/yearEndTax/components/ResultCardGroup.tsx
  hps/app/yearEndTax/components/ResultCardItem.tsx
  hps/app/yearEndTax/page.tsx
  hps/app/yearEndTax/utils/calculateRefund.ts
  hps/components/atoms/Title.tsx
  hps/constants/consumptionData.ts
  hps/lib/actions/.keep
  hps/lib/actions/getTaxInputs.ts
  hps/lib/db.ts
Labels: feat

#39 [Fix] User 테이블에 직장인여부 column 추가
  hps/backup_hps.sql
Labels: chore

#43 [Design] 하단 바 위치 조정
  hps/components/molcules/BarGraph.tsx
  hps/components/organisms/BottomTab/BottomTabBar.tsx
  hps/components/organisms/BottomTab/TabBarItem.tsx
Labels: design

#47 [Fix] SalaryBarGraph 하얀 부분 안 보이는 문제 해결
  hps/app/spendList/components/SpendAnalysis.tsx
  hps/app/spendList/utils/spending.ts
  hps/components/molcules/SalaryBarGraph.tsx
Labels: chore

#44 [Feat] Mainpage - 상단 Nav바 & 급여 카드 퍼블리싱 & 구현
  hps/app/components/MainNav.tsx
  hps/app/components/SalaryBox.tsx
  hps/app/globals.css
  hps/app/layout.tsx
  hps/app/page.tsx
  hps/app/yearEndTax/page.tsx
  hps/lib/actions/getTaxInputs.ts
  hps/lib/actions/salary-actions.ts
  hps/prisma/schema.prisma
  hps/public/ic_gomypage.svg
  hps/public/ic_pig.svg
  hps/public/ic_thismonth_pay.svg
Labels: feat, design

#52 [Feat] 의미없는 소비 선택 페이지 기능 구현
  hps/app/globals.css
  hps/app/mypage/page.tsx
  hps/app/uselessSpending/components/CompleteButton.tsx
  hps/app/uselessSpending/components/SpendSelectorList.tsx
  hps/app/uselessSpending/components/SpendSelectorSection.tsx
  hps/app/uselessSpending/page.tsx
  hps/app/uselessSpending/utils/saveUselessSpending.ts
  hps/components/molcules/List.tsx
  hps/components/molcules/ListItem.tsx
  hps/constants/consumptionData.ts
  hps/eslint.config.mjs
  hps/lib/actions/useless-spending-actions.ts
Labels: feat

#50 [Feat] 연말정산 페이지 카드 비교 및 체크리스트 작업
  hps/app/yearEndTax/components/Card.tsx
  hps/app/yearEndTax/components/CheckList.tsx
  hps/app/yearEndTax/components/ResultCardGroup.tsx
  hps/app/yearEndTax/components/ResultCardItem.tsx
  hps/app/yearEndTax/page.tsx
  hps/app/yearEndTax/utils/calculateRate.ts
  hps/components/atoms/Checkbox.tsx
  hps/components/molcules/CheckBoxText.tsx
  hps/constants/cardData.ts
  hps/lib/actions/checkbox-action.ts
  hps/public/Img_CheckCard(Big).svg
  hps/public/Img_CheckCard(Small).svg
  hps/public/Img_CreditCard(Big).svg
  hps/public/Img_CreditCard(Small).svg
Labels: feat

#65 [Feat] 회원가입 기능 추가
  hps/app/login/page.tsx
  hps/app/signup/page.tsx
  hps/lib/actions/signup.ts
  hps/lib/actions/users.ts
  hps/lib/auth.ts
  hps/lib/validator.ts
  hps/prisma/schema.prisma
Labels: feat, design

#68 [Feat] login error 처리
  hps/lib/actions/login.ts
Labels: feat

#69 [Design] 폰트 글꼴 수정
  hps/app/login/page.tsx
  hps/app/signup/page.tsx
  hps/lib/actions/auth-actions.ts
  hps/lib/validator.ts
Labels: design

#66 [Feat] 마이페이지 DB연동 정보 수정 & 비밀번호 변경 & 로그아웃
  hps/app/mypage/components/ChangePassword.tsx
  hps/app/mypage/components/MyPageClient.tsx
  hps/app/mypage/components/ProfileItem.tsx
  hps/app/mypage/page.tsx
  hps/app/mypage/utils/.keep
  hps/components/atoms/Button.tsx
  hps/components/atoms/Input.tsx
  hps/lib/actions/users.ts
Labels: feat, design

#73 [Feat] 소비 관리 페이지 그래프 및 평가 문장 구현
  hps/app/consumption/components/ConsumptionGraph.tsx
  hps/app/consumption/components/ConsumptionRateText.tsx
  hps/app/consumption/components/ConsumptionRatio.tsx
  hps/app/consumption/page.tsx
  hps/app/consumption/utils/evaluation.ts
  hps/app/consumption/utils/recurring.ts
  hps/app/globals.css
  hps/app/spendList/components/SpendAnalysis.tsx
  hps/app/spendList/components/SpendList.tsx
  hps/app/spendList/utils/spending.ts
  hps/components/molcules/SalaryBarGraph.tsx
  hps/constants/consumptionData.ts
  hps/lib/actions/fixed-expense-actions.ts
  hps/lib/actions/salary-actions.ts
  hps/stories/SalaryBarGraph.stories.tsx
Labels: feat

#71 [Feat] 메인페이지 카테고리 별 원 구현
  hps/app/components/BubbleAnimation.tsx
  hps/app/components/HanaMonWithCard.tsx
  hps/app/components/SalaryBox.tsx
  hps/app/components/SalaryCircle.tsx
  hps/app/components/SalarySpendButton.tsx
  hps/app/globals.css
  hps/app/page.tsx
  hps/app/utils/salary.ts
  hps/components/organisms/BottomTab/BottomTabBar.tsx
  hps/lib/actions/salary-actions.ts
  hps/lib/actions/salary-summary.ts
  hps/package.json
  hps/pnpm-lock.yaml
  hps/public/cogwheel.svg
  hps/public/hanaMonWithGreenCard.svg
  hps/public/hanaMonWithRedCard.svg
  hps/public/hanaMonWithYellowCard.svg
  hps/tsconfig.json
Labels: feat, design

#77 [Fix] 회원가입 링크 설정
  hps/app/login/page.tsx
Labels: bug

#83 [Fix] spendlist page 수정
  hps/app/spendList/components/SpendList.tsx
  hps/app/spendList/page.tsx
  hps/app/spendList/utils/spending.ts
Labels: bug

#90 [Feat] 수입 내역 페이지
  hps/app/globals.css
  hps/app/incomeList/components/GoToIncomeButton.tsx
  hps/app/incomeList/components/IncomeList.tsx
  hps/app/incomeList/components/IncomeListMonthBar.tsx
  hps/app/incomeList/components/LineGraph.tsx
  hps/app/incomeList/components/month-toggle.tsx
  hps/app/incomeList/page.tsx
  hps/app/incomeList/utils/salary.ts
  hps/app/layout.tsx
  hps/components/molcules/CustomTooltip.tsx
  hps/components/molcules/LineGraph.tsx
  hps/components/molcules/List.tsx
  hps/components/molcules/ListItem.tsx
  hps/components/ui/button.tsx
  hps/components/ui/dropdown-menu.tsx
  hps/components/ui/select.tsx
  hps/lib/actions/salary-actions.ts
  hps/package.json
  hps/pnpm-lock.yaml
  hps/public/svgs/ic_cogWheel.svg
  hps/public/svgs/ic_pencil.svg
  hps/stories/LineGraph.stories.tsx
Labels: feat, design

#87 [Feat] 소비 관리 별돌이 구현
  hps/app/consumption/components/ConsumStar.tsx
  hps/app/consumption/components/ConsumptionGraph.tsx
  hps/app/consumption/components/GoSpendButton.tsx
  hps/app/consumption/page.tsx
  hps/app/consumption/utils/evaluation.ts
  hps/public/svgs/ic_chat.svg
Labels: feat, design

#85 [Feat] ToastMsg molcule 구현
  hps/components/molcules/ToastMsg.tsx
Labels: feat, design

#95 [Feat] 온보딩 페이지 구현
  hps/app/onboarding/components/onboarding.tsx
  hps/app/onboarding/page.tsx
  hps/public/svgs/ic_onboarding.svg
Labels: feat, design

#104 [design] 메인페이지 디자인 수정 by prof. Moon
  hps/app/components/BubbleAnimation.tsx
  hps/app/layout.tsx
  hps/app/page.tsx
  hps/package.json
  hps/pnpm-lock.yaml
Labels: bug, design

#106 [Refactor] 회원가입 & 로그인 & 마이페이지 UI 수정 및 코드 리팩토링
  hps/app/login/page.tsx
  hps/app/mypage/components/BusinessCode.tsx
  hps/app/mypage/components/ChangePassword.tsx
  hps/app/mypage/components/MyPageClient.tsx
  hps/app/mypage/components/ProfileItem.tsx
  hps/app/mypage/components/SelectBusinessEdit.tsx
  hps/app/signup/components/SelectBusiness.tsx
  hps/app/signup/page.tsx
  hps/components/atoms/Input.tsx
  hps/components/organisms/BottomTab/BottomTabBar.tsx
  hps/lib/actions/signup.ts
  hps/lib/validator.ts
Labels: feat, design

#103 [Design] Mainpage - 카드든 하나몬스터 오류 해결 및 디자인
  hps/app/components/HanaMonWithCard.tsx
  hps/app/components/SalaryBox.tsx
  hps/app/components/SalaryCircle.tsx
  hps/app/components/SalarySpendButton.tsx
  hps/public/hanaMonWithGreenCard.svg
  hps/public/hanaMonWithRedCard.svg
  hps/public/hanaMonWithYellowCard.svg
Labels: bug, design

#101 [Feat] ToastMsg 적용 작업
  hps/app/login/page.tsx
  hps/app/mypage/components/BusinessCode.tsx
  hps/app/mypage/components/ChangePassword.tsx
  hps/app/mypage/components/ProfileItem.tsx
  hps/app/signup/components/SelectBusiness.tsx
  hps/app/signup/page.tsx
  hps/components/molcules/ToastMsg.tsx
  hps/lib/actions/users.ts
  hps/public/svgs/ic_toastWarning.svg
Labels: feat

#114 [Design] 팡팡이 디자인을 수정
  hps/app/components/BubbleAnimation.tsx
  hps/app/components/SalaryCircle.tsx
  hps/app/page.tsx
  hps/package.json
  hps/pnpm-lock.yaml
Labels: design

#107 [Design] 수입 내역 Page - 디자인 수정
  hps/app/incomeList/components/IncomeList.tsx
  hps/app/incomeList/page.tsx
  hps/app/incomeList/utils/salary.ts
Labels: chore, design

#118 [Design] 수입 관리 페이지 작업
  hps/app/income/components/AdviceMessage.tsx
  hps/app/income/components/ProportionalBarGraph.tsx
  hps/app/income/page.tsx
  hps/lib/actions/salary-actions.ts
  hps/public/svgs/ic_question.svg
Labels: refactor, design

#120 [fix] 뒤로가기 수정 완료
  hps/app/components/SalarySpendButton.tsx
  hps/app/incomeList/page.tsx
  hps/app/incomeSource/components/CompleteButton.tsx
  hps/app/incomeSource/page.tsx
  hps/app/incomeSource/utils/saveIncomeSource.ts
  hps/app/spendList/page.tsx
  hps/components/templates/HeaderLayout.tsx
Labels: bug

#121 [Fix] main page 스크롤 제거
  hps/app/components/SalaryCircle.tsx
  hps/app/page.tsx
Labels: refactor, design

#124 [Feat] 수입 관리 페이지 - 다음 달 예측 수입 모달 기능
  hps/app/chat/components/StarChat.tsx
  hps/app/components/HanaMonWithCard.tsx
  hps/app/components/SalaryBox.tsx
  hps/app/components/SalarySpendButton.tsx
  hps/app/consumption/components/ConsumStar.tsx
  hps/app/consumption/components/ConsumptionGraph.tsx
  hps/app/consumption/components/ConsumptionRateText.tsx
  hps/app/consumption/utils/evaluation.ts
  hps/app/globals.css
  hps/app/income/components/AdviceMessage.tsx
  hps/app/income/components/Bar.tsx
  hps/app/income/components/GoIncomeListButton.tsx
  hps/app/income/components/IncomePredictionModal.tsx
  hps/app/income/components/Modal.tsx
  hps/app/income/components/NextMonthPredictionTrigger.tsx
  hps/app/income/components/ProportionalBarGraph.tsx
  hps/app/income/page.tsx
  hps/app/income/utils/incomeGraph.ts
  hps/app/not-found.tsx
  hps/app/signup/components/SelectBusiness.tsx
  hps/components/organisms/BottomTab/TabBarItem.tsx
  hps/pnpm-lock.yaml
  hps/prisma/schema.prisma
  hps/public/Img_CheckCard(Big).svg
  hps/public/Img_CheckCard(Small).svg
  hps/public/Img_CreditCard(Big).svg
  hps/public/Img_CreditCard(Small).svg
  hps/public/cogwheel.svg
  hps/public/images/card1.png
  hps/public/images/card2.png
  hps/public/images/card3.png
  hps/public/images/img_404hanaMon.svg
  hps/public/images/img_good.svg
  hps/public/images/img_hanaMonWithGreenCard.svg
  hps/public/images/img_hanaMonWithRedCard.svg
  hps/public/images/img_hanaMonWithYellowCard.svg
  hps/public/images/img_sad.svg
  hps/public/images/img_soso.svg
  hps/public/svgs/ic_file.svg
Labels: feat, design

#128 [Fix] 팡팡이 위치 변경 & 디비 통일
  hps/app/components/SalaryCircle.tsx
  hps/constants/incomeData.ts
  hps/lib/actions/salary-summary.ts
Labels: chore, design

#129 [Fix] qa 적용완료
  hps/app/api/chat/route.ts
  hps/app/api/prompt/route.ts
  hps/app/chat/components/UserChat.tsx
  hps/app/chat/page.tsx
  hps/app/components/SalaryBox.tsx
  hps/app/consumption/page.tsx
  hps/app/incomeList/components/IncomeList.tsx
  hps/app/incomeList/page.tsx
  hps/app/incomeSource/page.tsx
  hps/app/layout.tsx
  hps/app/mypage/apis/.keep
  hps/app/mypage/constants/.keep
  hps/app/mypage/hooks/.keep
  hps/app/page.tsx
  hps/app/session.tsx
  hps/app/spendList/page.tsx
  hps/hooks/.keep
Labels: bug

#130 [Chore] user2,3 데이터 추가
  hps/app/components/SalaryCircle.tsx
  hps/constants/incomeData.ts
Labels: chore

#145 [Refactor] 소비 관리 페이지 - 소비 관리 로직 수정
  hps/app/components/HanaMonWithCard.tsx
  hps/app/consumption/components/ConsumStar.tsx
  hps/app/consumption/components/ConsumptionGraph.tsx
  hps/app/consumption/components/ConsumptionRateText.tsx
  hps/app/consumption/components/ConsumptionRatio.tsx
  hps/app/consumption/components/GoSpendButton.tsx
  hps/app/consumption/page.tsx
  hps/app/consumption/utils/evaluation.ts
  hps/app/income/page.tsx
  hps/components/templates/HeaderLayout.tsx
  hps/lib/actions/salary-actions.ts
  hps/public/svgs/ic_chat.svg
Labels: refactor

#148 [refactor] 수입내역scroll추가
  hps/app/incomeList/page.tsx
  hps/prisma/schema.prisma
Labels: chore, refactor

#153 [Refactor] 소비,수입 db 수정
  backup_hps.sql
  hps/constants/consumptionData.ts
Labels: chore, refactor

#150 [Feat] MainPage - 카드 든 별돌이 다음 달 예측 수입 기준으로 지출 반영해서 카드색 로직 변경
  hps/app/components/HanaMonWithCard.tsx
  hps/app/components/SalaryBox.tsx
Labels: feat

#154 [Chore] Income Page - 전체 화면 스크롤 제거 & 수입 관리하러 가기 버튼 제거
  hps/app/globals.css
  hps/app/income/page.tsx
  hps/app/incomeList/page.tsx
Labels: chore
