Repository Hanaro-Eureka/HPS, pull requests merged in 2025-07, with the labels that each got.

#169 [Refactor]: income DB 6월까지 적용
  backup_hps.sql
Labels: chore, refactor

#168 [Feat] 전문상담사 페이지 이미지 추가 및 변경
  hps/app/counselor/page.tsx
  hps/public/svgs/expertchat.svg
Labels: chore

#170 [Docs] README 최종 업데이트
  README.md
Labels: docs
